#! /usr/bin/env python3.11

"""
Podman wrapper that turns on caching forcefully. This is to be used for builds in GitHub Actions.
"""
import os
import shlex
import subprocess
import sys


def main():
    # podman run/build ...
    first, second, *rest = sys.argv
    # args = ["/home/linuxbrew/.linuxbrew/bin/podman", second]
    args = ["docker"]
    if second == "build":
        args.append("buildx")
        args.append("build")
    else:
        args.append(second)

    for arg in rest:
        if arg == '--no-cache':
            continue
        args.append(arg)
    # # https://github.com/containers/podman/issues/22044
    # if second in ("build", "run"):
    #     args.insert(2, "--network=slirp4netns")
    if second == "build":
        args.append("-fContainerfile")
    if second == "build" and "CACHE_IMAGE" in os.environ:
        # args.append("--layers")
        # args.append("--retry=10")
        args.append(f"--cache-from={os.environ['CACHE_IMAGE']}")
        # todo: conditionally, don't do this for PRs?
        args.append(f"--cache-to={os.environ['CACHE_IMAGE']}")

    print("+", shlex.join(args), file=sys.stderr)
    ret = subprocess.call(args=args)

    exit(ret)


if __name__ == '__main__':
    main()
