on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:

      # https://github.com/marketplace/actions/maximize-build-disk-space
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 256
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - uses: "actions/checkout@v4"

      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"

      - name: Workaround https://github.com/containers/podman/issues/22152#issuecomment-2027705598
        run: sudo apt-get remove -y podman crun

      - uses: actions/cache@v3
        with:
          path: |
            /home/linuxbrew/.linuxbrew
          key: linuxbrew

      - name: Install podman
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          /home/linuxbrew/.linuxbrew/bin/brew install podman

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # I'm too lazy to take care of this myself, see the packaged action above

#      - name: Free up disk space
#        run: |
#          sudo rm -rf /usr/share/dotnet &
#          sudo rm -rf /usr/local/lib/android &
#          sudo rm -rf /opt/ghc &
#          sudo rm -rf /usr/local/share/boost &
#          sudo rm -rf /opt/hostedtoolcache/CodeQL &
#          # this is where python lives
#          # sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
#
#          sudo docker image prune --all --force &
#
#          sudo swapoff -a
#          sudo rm -f /mnt/swapfile
#
#          wait
#        shell: bash

      - run: |
          make all PATH="${{ github.workspace }}/.github/path:/home/linuxbrew/.linuxbrew/bin:${PATH}" RELEASE="cache" DATE="cache"
        shell: bash
        env:
          CACHE_IMAGE: ghcr.io/${{ github.repository }}/workbench-images/build-cache
        working-directory: base

      - run: |
          make all PATH="${{ github.workspace }}/.github/path:/home/linuxbrew/.linuxbrew/bin:${PATH}" RELEASE="cache" DATE="cache"
        shell: bash
        env:
          CACHE_IMAGE: ghcr.io/${{ github.repository }}/workbench-images/build-cache
        working-directory: cuda-layer
